export * from "./dataset";

export const HOME_ROUTE = "/";
export const SIGN_IN_ROUTE = "/auth/login";
export const FORGOT_PASSWORD_ROUTE = "/auth/forgot";
export const RESET_PASSWORD_ROUTE = "/auth/reset";
export const VERIFY_EMAIL_ROUTE = "/auth/verify";
export const ADMIN_ROUTE = "/admin";
export const ABOUT_ROUTE = "/about";
export const CONTACT_ROUTE = "/contact";
export const PRIVACY_POLICY_ROUTE = "/privacy";
export const PROFILE_ROUTE = "/profile";
export const PROFILE_SETTINGS_ROUTE = "/profile/settings";
export const PROFILE_BOOKMARKS_ROUTE = "/profile/bookmarks";
export const PROFILE_DATASETS_ROUTE = "/profile/datasets";
export const PROFILE_DISCUSSIONS_ROUTE = "/profile/discussions";
export const CONTRIBUTE_ROUTE = "/contribute";
export const CONTRIBUTE_EXTERNAL_ROUTE = "/contribute/external";
export const CONTRIBUTE_DONATION_ROUTE = "/contribute/donation";
export const CONTRIBUTE_EXTERNAL_FORM_ROUTE = "/contribute/external/form";
export const CONTRIBUTE_DONATION_FORM_ROUTE = "/contribute/donation/form";
export const STATIC_FILES_ROUTE = "/api/static";
