import type { Prisma } from "@prisma/client";
import bcryptjs from "bcryptjs";

const dummyUserId = "0";
const password = bcryptjs.hashSync("p", 10);

export const roles: Prisma.RoleCreateManyInput[] = [
  {
    id: "ADMIN",
    canEditRoles: true,
  },
  {
    id: "LIBRARIAN",
  },
  {
    id: "CURATOR",
  },
  {
    id: "BASIC",
  },
];

export const introductoryPapers: Prisma.DatasetPaperCreateManyInput[] =
  Array.from({ length: 10 }, (_, i) => {
    return {
      id: `${i + 1}`,
      title: `Very Scientific Paper Number ${i + 1}`,
      authors: ["John Lorenzini", "Andrew Wang"],
      venue: "Journal of Science",
      year: 2024,
      url: "https://example.com",
    };
  });

export const users: Prisma.UserCreateManyInput[] = [
  {
    id: dummyUserId,
    email: "dummy@guci.edu",
    name: "dummy",
    password,
  },
  {
    id: "admin",
    email: "admin@uci.edu",
    name: "Admin",
    roleId: "ADMIN",
    password,
  },
  {
    id: "librarian",
    email: "librarian@uci.edu",
    name: "Librarian",
    roleId: "LIBRARIAN",
    password,
  },
  {
    id: "curator",
    email: "curator@uci.edu",
    name: "Curator",
    roleId: "CURATOR",
    password,
  },
];

export const datasets: Omit<
  Required<Prisma.DatasetCreateManyInput>,
  "createdAt" | "updatedAt" | "zipFileId"
>[] = [
  {
    id: 53,
    userId: dummyUserId,
    status: "APPROVED",
    donatedAt: new Date("1988-07-01"),
    yearCreated: 1936,
    title: "Iris",
    subtitle: "SUBTITLE SUBTITLE SUBTITLE SUBTITLE",
    doi: "10.24432/C56C76",
    description:
      "A small classic dataset from Fisher, 1936. One of the earliest known datasets used for evaluating classification methods.",
    area: "BIOLOGY",
    characteristics: ["TABULAR"],
    tasks: ["CLASSIFICATION"],
    featureTypes: ["REAL"],
    isTabular: true,
    instanceCount: 150,
    featureCount: 4,
    hasGraphics: true,
    isAvailablePython: true,
    viewCount: 669763,
    downloadCount: 191103,
    slug: "iris",
    externalLink: null,
    hasMissingValues: false,
    introductoryPaperId: "1",
  },
  {
    id: 45,
    userId: dummyUserId,
    status: "APPROVED",
    donatedAt: new Date("1988-07-01"),
    yearCreated: 1989,
    title: "Heart Disease",
    subtitle: "SUBTITLE SUBTITLE SUBTITLE SUBTITLE SUBTITLE SUBTITLE SUBTITLE",
    doi: "10.24432/C5DW2B",
    description:
      "4 databases: Cleveland, Hungary, Switzerland, and the VA Long Beach.",
    area: "BIOLOGY",
    characteristics: ["MULTIVARIATE"],
    tasks: ["CLASSIFICATION"],
    featureTypes: ["CATEGORICAL", "INTEGER", "REAL"],
    isTabular: false,
    instanceCount: 303,
    featureCount: 13,
    hasGraphics: false,
    isAvailablePython: true,
    viewCount: 497006,
    downloadCount: 125605,
    slug: "heart+disease",
    externalLink: null,
    hasMissingValues: true,
    introductoryPaperId: "2",
  },
  {
    id: 186,
    userId: dummyUserId,
    status: "APPROVED",
    donatedAt: new Date("2009-10-07"),
    yearCreated: 2009,
    title: "Wine Quality",
    subtitle: null,
    doi: "10.24432/C56S3T",
    description:
      "Two datasets are included, related to red and white vinho verde wine samples, from the north of Portugal. The goal is to model wine quality based on physicochemical tests (see [Cortez et al., 2009], http://www3.dsi.uminho.pt/pcortez/wine/).",
    characteristics: ["MULTIVARIATE"],
    area: "BUSINESS",
    tasks: ["CLASSIFICATION", "REGRESSION"],
    featureTypes: ["REAL"],
    isTabular: true,
    instanceCount: 4898,
    featureCount: 12,
    hasGraphics: false,
    isAvailablePython: true,
    viewCount: 330143,
    downloadCount: 105932,
    slug: "wine+quality",
    externalLink: null,
    hasMissingValues: true,
    introductoryPaperId: "3",
  },
  {
    id: 2,
    userId: dummyUserId,
    status: "APPROVED",
    donatedAt: new Date("2012-02-14"),
    yearCreated: 2009,
    title: "Adult",
    subtitle: null,
    doi: "10.24432/C56S3T",
    description:
      'Predict whether annual income of an individual exceeds $50K/yr based on census data. Also known as "Census Income" dataset.',
    characteristics: ["MULTIVARIATE"],
    area: "SOCIAL_SCIENCE",
    tasks: ["CLASSIFICATION"],
    featureTypes: ["CATEGORICAL", "INTEGER"],
    isTabular: true,
    instanceCount: 48842,
    featureCount: 14,
    hasGraphics: false,
    isAvailablePython: true,
    viewCount: 310010,
    downloadCount: 80360,
    slug: "adult",
    externalLink: null,
    hasMissingValues: true,
    introductoryPaperId: "4",
  },
  {
    id: 17,
    userId: dummyUserId,
    status: "APPROVED",
    donatedAt: new Date("1995-11-01"),
    yearCreated: 1993,
    title: "Breast Cancer Wisconsin (Diagnostic)",
    subtitle: null,
    doi: "10.24432/C5DW2B",
    description: "Diagnostic Wisconsin Breast Cancer Database.",
    characteristics: ["MULTIVARIATE"],
    area: "HEALTH_AND_MEDICINE",
    tasks: ["CLASSIFICATION"],
    featureTypes: ["REAL"],
    isTabular: true,
    instanceCount: 569,
    featureCount: 30,
    hasGraphics: false,
    isAvailablePython: true,
    viewCount: 298689,
    downloadCount: 78091,
    slug: "breast+cancer+wisconsin+diagnostic",
    externalLink: null,
    hasMissingValues: true,
    introductoryPaperId: "5",
  },
  {
    id: 1031,
    userId: dummyUserId,
    status: "APPROVED",
    donatedAt: new Date("2024-07-11"),
    yearCreated: 2024,
    title: "Dataset for Assessing Mathematics Learning in Higher Education",
    subtitle: "SUBTITLE SUBTITLE SUBTITLE SUBTITLE SUBTITLE SUBTITLE",
    doi: "10.34620/dadosipb/PW3OWY",
    description:
      "MathE is a mathematical platform developed under the MathE project (mathe.pixel-online.org). The dataset has 9546 answers to questions in the Mathematical topics taught in higher education. The file has eight features, named: Student ID, Student Country, Question ID, Type of answer (correct or incorrect), Question level (basic or advanced), Math Topic, Math Subtopic, and Question Keywords. The question level was associated with the professor who submitted the question. The data was obtained from February 2019 until December 2023.",
    characteristics: ["TABULAR"],
    area: "EDUCATION",
    tasks: ["CLASSIFICATION", "REGRESSION", "CLUSTERING"],
    featureTypes: ["REAL", "CATEGORICAL", "INTEGER"],
    isTabular: false,
    instanceCount: 10375,
    featureCount: 8,
    hasGraphics: false,
    isAvailablePython: false,
    viewCount: 10375,
    downloadCount: 3459,
    slug: "dataset+for+assessing+mathematics+learning+in+higher+education",
    externalLink: null,
    hasMissingValues: true,
    introductoryPaperId: "6",
  },
  {
    id: 1074,
    userId: dummyUserId,
    status: "PENDING",
    donatedAt: new Date("2024-10-15"),
    yearCreated: 2024,
    title: "Nvidia Market Customer segmentation data",
    subtitle: null,
    doi: null,
    description:
      "The Nvidia Market Customer Segmentation dataset provides a comprehensive analysis of sales and market dynamics for Nvidia's product offerings across various global regions from 1993 to 2024. This synthetic dataset includes over 39,000 entries, capturing key variables such as product categories (Gaming, AI, Data Center, OEM), specific product names (e.g., RTX 3080, Tesla V100), customer segments (Gamers, AI Researchers, Cloud Providers, Educational Institutions), and regions (North America, Europe, APAC, and more). It details customer purchasing behavior, including revenue data, units sold, marketing expenditures, customer satisfaction scores, and customer retention rates.",
    characteristics: ["TABULAR"],
    area: "BUSINESS",
    tasks: ["CLASSIFICATION", "REGRESSION", "CLUSTERING"],
    featureTypes: ["REAL", "CATEGORICAL", "INTEGER"],
    isTabular: false,
    instanceCount: 39298,
    featureCount: 19,
    hasGraphics: false,
    isAvailablePython: false,
    viewCount: 0,
    downloadCount: 0,
    slug: "nvidia+market+customer+segmentation+data",
    externalLink: null,
    hasMissingValues: true,
    introductoryPaperId: "7",
  },
  {
    id: 388,
    userId: dummyUserId,
    status: "REJECTED",
    donatedAt: new Date("2017-05-24"),
    yearCreated: 2017,
    title: "Epileptic Seizure Recognition",
    subtitle: null,
    doi: "10.24432/C5G308",
    description:
      "This dataset is a pre-processed and re-structured/reshaped version of a very commonly used dataset featuring epileptic seizure detection.",
    characteristics: ["MULTIVARIATE", "TIME_SERIES"],
    area: "HEALTH_AND_MEDICINE",
    tasks: ["CLASSIFICATION", "CLUSTERING"],
    featureTypes: ["INTEGER", "REAL"],
    isTabular: true,
    instanceCount: 11500,
    featureCount: 1,
    hasGraphics: false,
    isAvailablePython: false,
    viewCount: 15897,
    downloadCount: 2032,
    slug: "epileptic+seizure+recognition",
    externalLink: null,
    hasMissingValues: true,
    introductoryPaperId: "8",
  },
  {
    id: 939,
    userId: dummyUserId,
    status: "PENDING",
    donatedAt: new Date("2023-12-07"),
    yearCreated: 2023,
    title: "My Pending Externally Linked Dataset",
    subtitle: null,
    doi: "10.5281/zenodo.7669442",
    description:
      "This is a test dataset to see if the website can handle pending external links",
    characteristics: ["TABULAR", "IMAGE"],
    area: "HEALTH_AND_MEDICINE",
    tasks: ["CLASSIFICATION"],
    featureTypes: ["REAL", "CATEGORICAL", "INTEGER"],
    isTabular: false,
    instanceCount: 782,
    featureCount: 59,
    hasGraphics: false,
    isAvailablePython: false,
    viewCount: 18985,
    downloadCount: 4043,
    slug: "test+pending",
    externalLink: "https://zenodo.org/records/7669442",
    hasMissingValues: true,
    introductoryPaperId: "9",
  },
  {
    id: 938,
    userId: dummyUserId,
    status: "APPROVED",
    donatedAt: new Date("2023-12-07"),
    yearCreated: 2023,
    title: "Regensburg Pediatric Appendicitis",
    subtitle: null,
    doi: "10.5281/zenodo.7669442",
    description:
      "This repository holds the data from a cohort of pediatric patients with suspected appendicitis admitted with abdominal pain to Children’s Hospital St. Hedwig in Regensburg, Germany, between 2016 and 2021. Each patient has (potentially multiple) ultrasound (US) images, aka views, tabular data comprising laboratory, physical examination, scoring results and ultrasonographic findings extracted manually by the experts, and three target variables, namely, diagnosis, management and severity.",
    characteristics: ["TABULAR", "IMAGE"],
    area: "HEALTH_AND_MEDICINE",
    tasks: ["CLASSIFICATION"],
    featureTypes: ["REAL", "CATEGORICAL", "INTEGER"],
    isTabular: false,
    instanceCount: 782,
    featureCount: 59,
    hasGraphics: false,
    isAvailablePython: false,
    viewCount: 18985,
    downloadCount: 4043,
    slug: "regensburg+pediatric+appendicitis",
    externalLink: "https://zenodo.org/records/7669442",
    hasMissingValues: true,
    introductoryPaperId: "10",
  },
];
