import type { Prisma } from "@prisma/client";
import bcryptjs from "bcryptjs";

import { prisma } from "@/lib/db/prisma";

const dummyUserId = "0";
const dummyPassword = bcryptjs.hashSync("password", 10);

const roles: Prisma.RoleCreateManyInput[] = [
  {
    id: "ADMIN",
    canEditRoles: true,
  },
  {
    id: "LIBRARIAN",
  },
  {
    id: "CURATOR",
  },
  {
    id: "BASIC",
  },
];

const users: Prisma.UserCreateManyInput[] = [
  {
    id: dummyUserId,
    email: "test0@uci.edu",
    name: "test0",
    password: dummyPassword,
  },
  {
    id: "admin",
    email: "ucirepository@uci.edu",
    name: "admin",
    password: bcryptjs.hashSync("password", 10),
    roleId: "ADMIN",
  },
];

const datasets: Omit<
  Required<Prisma.DatasetCreateManyInput>,
  "createdAt" | "updatedAt"
>[] = [
  {
    id: 53,
    userId: dummyUserId,
    status: "APPROVED",
    donatedAt: new Date("1988-07-01"),
    yearCreated: 1936,
    title: "Iris",
    subtitle: null,
    doi: "10.24432/C56C76",
    abstract:
      "A small classic dataset from Fisher, 1936. One of the earliest known datasets used for evaluating classification methods.",
    area: "BIOLOGY",
    characteristics: ["TABULAR"],
    tasks: ["CLASSIFICATION"],
    featureTypes: ["REAL"],
    isTabular: true,
    instanceCount: 150,
    featureCount: 4,
    hasGraphics: true,
    isAvailablePython: true,
    viewCount: 669763,
    downloadCount: 191103,
    slug: "iris",
  },
  {
    id: 45,
    userId: dummyUserId,
    status: "APPROVED",
    donatedAt: new Date("1988-07-01"),
    yearCreated: 1989,
    title: "Heart Disease",
    subtitle: null,
    doi: "10.24432/C5DW2B",
    abstract:
      "4 databases: Cleveland, Hungary, Switzerland, and the VA Long Beach.",
    area: "BIOLOGY",
    characteristics: ["MULTIVARIATE"],
    tasks: ["CLASSIFICATION"],
    featureTypes: ["CATEGORICAL", "INTEGER", "REAL"],
    isTabular: false,
    instanceCount: 303,
    featureCount: 13,
    hasGraphics: false,
    isAvailablePython: true,
    viewCount: 497006,
    downloadCount: 125605,
    slug: "heart+disease",
  },
  {
    id: 186,
    userId: dummyUserId,
    status: "APPROVED",
    donatedAt: new Date("2009-10-07"),
    yearCreated: 2009,
    title: "Wine Quality",
    subtitle: null,
    doi: "10.24432/C56S3T",
    abstract:
      "Two datasets are included, related to red and white vinho verde wine samples, from the north of Portugal. The goal is to model wine quality based on physicochemical tests (see [Cortez et al., 2009], http://www3.dsi.uminho.pt/pcortez/wine/).",
    characteristics: ["MULTIVARIATE"],
    area: "BUSINESS",
    tasks: ["CLASSIFICATION", "REGRESSION"],
    featureTypes: ["REAL"],
    isTabular: true,
    instanceCount: 4898,
    featureCount: 12,
    hasGraphics: false,
    isAvailablePython: true,
    viewCount: 330143,
    downloadCount: 105932,
    slug: "wine+quality",
  },
  {
    id: 2,
    userId: dummyUserId,
    status: "APPROVED",
    donatedAt: new Date("2012-02-14"),
    yearCreated: 2009,
    title: "Adult",
    subtitle: null,
    doi: "10.24432/C56S3T",
    abstract:
      'Predict whether annual income of an individual exceeds $50K/yr based on census data. Also known as "Census Income" dataset.',
    characteristics: ["MULTIVARIATE"],
    area: "SOCIAL_SCIENCE",
    tasks: ["CLASSIFICATION"],
    featureTypes: ["CATEGORICAL", "INTEGER"],
    isTabular: true,
    instanceCount: 48842,
    featureCount: 14,
    hasGraphics: false,
    isAvailablePython: true,
    viewCount: 310010,
    downloadCount: 80360,
    slug: "adult",
  },
  {
    id: 17,
    userId: dummyUserId,
    status: "APPROVED",
    donatedAt: new Date("1995-11-01"),
    yearCreated: 1993,
    title: "Breast Cancer Wisconsin (Diagnostic)",
    subtitle: null,
    doi: "10.24432/C5DW2B",
    abstract: "Diagnostic Wisconsin Breast Cancer Database.",
    characteristics: ["MULTIVARIATE"],
    area: "HEALTH_AND_MEDICINE",
    tasks: ["CLASSIFICATION"],
    featureTypes: ["REAL"],
    isTabular: true,
    instanceCount: 569,
    featureCount: 30,
    hasGraphics: false,
    isAvailablePython: true,
    viewCount: 298689,
    downloadCount: 78091,
    slug: "breast+cancer+wisconsin+diagnostic",
  },
  {
    id: 1031,
    userId: dummyUserId,
    status: "APPROVED",
    donatedAt: new Date("2024-07-11"),
    yearCreated: 2024,
    title: "Dataset for Assessing Mathematics Learning in Higher Education",
    subtitle: null,
    doi: " https://doi.org/10.34620/dadosipb/PW3OWY",
    abstract:
      "MathE is a mathematical platform developed under the MathE project (mathe.pixel-online.org). The dataset has 9546 answers to questions in the Mathematical topics taught in higher education. The file has eight features, named: Student ID, Student Country, Question ID, Type of answer (correct or incorrect), Question level (basic or advanced), Math Topic, Math Subtopic, and Question Keywords. The question level was associated with the professor who submitted the question. The data was obtained from February 2019 until December 2023.",
    characteristics: ["TABULAR"],
    area: "EDUCATION",
    tasks: ["CLASSIFICATION", "REGRESSION", "CLUSTERING"],
    featureTypes: ["REAL", "CATEGORICAL", "INTEGER"],
    isTabular: false,
    instanceCount: 10375,
    featureCount: 8,
    hasGraphics: false,
    isAvailablePython: false,
    viewCount: 10375,
    downloadCount: 3459,
    slug: "dataset+for+assessing+mathematics+learning+in+higher+education",
  },
  {
    id: 1074,
    userId: dummyUserId,
    status: "PENDING",
    donatedAt: new Date("2024-10-15"),
    yearCreated: 2024,
    title: "Nvidia Market Customer segmentation data",
    subtitle: null,
    doi: null,
    abstract:
      "The Nvidia Market Customer Segmentation dataset provides a comprehensive analysis of sales and market dynamics for Nvidia's product offerings across various global regions from 1993 to 2024. This synthetic dataset includes over 39,000 entries, capturing key variables such as product categories (Gaming, AI, Data Center, OEM), specific product names (e.g., RTX 3080, Tesla V100), customer segments (Gamers, AI Researchers, Cloud Providers, Educational Institutions), and regions (North America, Europe, APAC, and more). It details customer purchasing behavior, including revenue data, units sold, marketing expenditures, customer satisfaction scores, and customer retention rates.",
    characteristics: ["TABULAR"],
    area: "BUSINESS",
    tasks: ["CLASSIFICATION", "REGRESSION", "CLUSTERING"],
    featureTypes: ["REAL", "CATEGORICAL", "INTEGER"],
    isTabular: false,
    instanceCount: 39298,
    featureCount: 19,
    hasGraphics: false,
    isAvailablePython: false,
    viewCount: 0,
    downloadCount: 0,
    slug: "nvidia+market+customer+segmentation+data",
  },
  {
    id: 388,
    userId: dummyUserId,
    status: "REJECTED",
    donatedAt: new Date("2017-05-24"),
    yearCreated: 2017,
    title: "Epileptic Seizure Recognition",
    subtitle: null,
    doi: "10.24432/C5G308",
    abstract:
      "This dataset is a pre-processed and re-structured/reshaped version of a very commonly used dataset featuring epileptic seizure detection.",
    characteristics: ["MULTIVARIATE", "TIME_SERIES"],
    area: "HEALTH_AND_MEDICINE",
    tasks: ["CLASSIFICATION", "CLUSTERING"],
    featureTypes: ["INTEGER", "REAL"],
    isTabular: true,
    instanceCount: 11500,
    featureCount: 1,
    hasGraphics: true,
    isAvailablePython: false,
    viewCount: 15897,
    downloadCount: 2032,
    slug: "epileptic+seizure+recognition",
  },
];

async function seed() {
  await prisma.$transaction([
    prisma.role.createMany({
      data: roles,
    }),
    prisma.user.createMany({
      data: users,
    }),
    prisma.dataset.createMany({
      data: datasets,
    }),
  ]);
}

seed().then();
