server {
  listen 8080;
  listen 8443 ssl;

  # SSL certs are mounted from the host into the container.
  ssl_certificate /etc/nginx/certs/archive_chain.crt;
  ssl_certificate_key /etc/nginx/certs/archive.key;
  ssl_password_file /etc/nginx/certs/pass;

  # Limit upload size for dataset donation.
  client_max_body_size 1G;

  location / {
      proxy_pass http://localhost:3000;
  }
}
