server {
  listen 8080;
  listen 8443 ssl;

  # SSL certs are mounted from the host into the container.
  ssl_certificate /etc/nginx/certs/archive-beta_ics_uci_edu_chain.pem;
  ssl_certificate_key /etc/nginx/certs/new_archive-beta.key;
  ssl_password_file /etc/nginx/certs/pass;

  # Limit upload size for dataset donation.
  client_max_body_size 512M;

  location / {
      proxy_pass http://localhost:3000;
  }
}
