services:
  database:
    image: postgres:alpine
    container_name: database
    restart: unless-stopped
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - ./compose.sql:/docker-entrypoint-initdb.d/compose.sql
